
package secfox.soc.integration.sni.wsdl.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-27T15:08:03.967+08:00
 * Generated source version: 3.0.2
 * 
 */
public final class ServiceMBeanPortType_ServiceMBeanPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.soa.system.soc.secfox/", "ServiceMBean");

    private ServiceMBeanPortType_ServiceMBeanPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiceMBean.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServiceMBean ss = new ServiceMBean(wsdlURL, SERVICE_NAME);
        ServiceMBeanPortType port = ss.getServiceMBeanPort();  
        
        {
        System.out.println("Invoking getLinkFlow...");
        int _getLinkFlow_periodType = 0;
        java.util.List<secfox.soc.integration.sni.wsdl.client.LongArray> _getLinkFlow__return = port.getLinkFlow(_getLinkFlow_periodType);
        System.out.println("getLinkFlow.result=" + _getLinkFlow__return);


        }
        {
        System.out.println("Invoking deleteUser...");
        int _deleteUser_userId = 0;
        int _deleteUser__return = port.deleteUser(_deleteUser_userId);
        System.out.println("deleteUser.result=" + _deleteUser__return);


        }
        {
        System.out.println("Invoking updateDeviceBasicInfo...");
        long _updateDeviceBasicInfo_ciid = 0;
        java.util.List<java.lang.Object> _updateDeviceBasicInfo_properties = null;
        int _updateDeviceBasicInfo__return = port.updateDeviceBasicInfo(_updateDeviceBasicInfo_ciid, _updateDeviceBasicInfo_properties);
        System.out.println("updateDeviceBasicInfo.result=" + _updateDeviceBasicInfo__return);


        }
        {
        System.out.println("Invoking getDeviceObjectList...");
        java.util.List<secfox.soc.integration.sni.wsdl.client.DeviceObject> _getDeviceObjectList__return = port.getDeviceObjectList();
        System.out.println("getDeviceObjectList.result=" + _getDeviceObjectList__return);


        }
        {
        System.out.println("Invoking addSecurityPolicy...");
        java.util.List<java.lang.Object> _addSecurityPolicy_properties = null;
        boolean _addSecurityPolicy_transform = false;
        int _addSecurityPolicy__return = port.addSecurityPolicy(_addSecurityPolicy_properties, _addSecurityPolicy_transform);
        System.out.println("addSecurityPolicy.result=" + _addSecurityPolicy__return);


        }
        {
        System.out.println("Invoking deleteDevice...");
        long _deleteDevice_ccid = 0;
        int _deleteDevice__return = port.deleteDevice(_deleteDevice_ccid);
        System.out.println("deleteDevice.result=" + _deleteDevice__return);


        }
        {
        System.out.println("Invoking updateUser...");
        int _updateUser_userId = 0;
        java.util.List<java.lang.Object> _updateUser_properties = null;
        int _updateUser__return = port.updateUser(_updateUser_userId, _updateUser_properties);
        System.out.println("updateUser.result=" + _updateUser__return);


        }
        {
        System.out.println("Invoking updateAlertStatus...");
        long _updateAlertStatus_alertId = 0;
        int _updateAlertStatus__return = port.updateAlertStatus(_updateAlertStatus_alertId);
        System.out.println("updateAlertStatus.result=" + _updateAlertStatus__return);


        }
        {
        System.out.println("Invoking insertUser...");
        int _insertUser_userId = 0;
        java.util.List<java.lang.Object> _insertUser_properties = null;
        int _insertUser__return = port.insertUser(_insertUser_userId, _insertUser_properties);
        System.out.println("insertUser.result=" + _insertUser__return);


        }
        {
        System.out.println("Invoking distributeIP...");
        java.lang.String _distributeIP_ip = "";
        java.lang.String _distributeIP_subnet = "";
        java.lang.Integer _distributeIP_status = null;
        int _distributeIP__return = port.distributeIP(_distributeIP_ip, _distributeIP_subnet, _distributeIP_status);
        System.out.println("distributeIP.result=" + _distributeIP__return);


        }

        System.exit(0);
    }

}
