package secfox.soc.integration.sni.wsdl.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2014-11-27T15:08:04.015+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "ServiceMBean", 
                  wsdlLocation = "http://172.10.1.160:8199/services/interfaces?wsdl",
                  targetNamespace = "http://service.soa.system.soc.secfox/") 
public class ServiceMBean extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.soa.system.soc.secfox/", "ServiceMBean");
    public final static QName ServiceMBeanPort = new QName("http://service.soa.system.soc.secfox/", "ServiceMBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.10.1.160:8199/services/interfaces?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceMBean.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.10.1.160:8199/services/interfaces?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceMBean(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceMBean(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceMBean() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public ServiceMBean(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public ServiceMBean(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public ServiceMBean(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }    

    /**
     *
     * @return
     *     returns ServiceMBeanPortType
     */
    @WebEndpoint(name = "ServiceMBeanPort")
    public ServiceMBeanPortType getServiceMBeanPort() {
        return super.getPort(ServiceMBeanPort, ServiceMBeanPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceMBeanPortType
     */
    @WebEndpoint(name = "ServiceMBeanPort")
    public ServiceMBeanPortType getServiceMBeanPort(WebServiceFeature... features) {
        return super.getPort(ServiceMBeanPort, ServiceMBeanPortType.class, features);
    }

}
